DROP TABLE IF EXISTS teachers_group CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS email_verifications;
DROP TABLE IF EXISTS users CASCADE;